import { EmptyState } from "@/components/ui/EmptyState"
import { PlayCircle } from "lucide-react"
import type { Metadata } from "next"

export const metadata: Metadata = { title: "YouTube — BrainVault" }

export default function YoutubePage() {
  return (
    <div className="p-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-2xl font-bold text-foreground mb-1">YouTube</h1>
        <p className="text-muted-foreground text-sm mb-8">
          Videos and playlists — transcribed, chapter-summarised, and indexed for semantic search.
        </p>
        <EmptyState
          icon={<PlayCircle size={28} className="text-red-400" />}
          title="No YouTube videos saved yet"
          description="Paste a YouTube video or playlist URL in the dashboard to get started."
          hint="Full transcripts are extracted for free — no API key needed. Chapter summaries generated by AI."
        />
      </div>
    </div>
  )
}
